### ISSUE TITLE
JIntellitype.setLibraryLocation(File) ignores absolute files

### ISSUE THREAD

**Issue by BjoernPetersen** [melloware/jintellitype#15]
The <code>JIntellitype.setLibraryLocation(File)</code> method checks whether a file already has an absolute path and if not, generates the absolute path and stores it. If the file already is absolute however, it is simply ignored and not stored.

A workaround for this bug is calling <code>JIntellitype.setLibraryLocation(String)</code> with the file's absolute path.

**Comment by melloware** [comment]
Thanks for the PR!
