### ISSUE TITLE
Can't load library dll from inside of the Spring Boot JAR application

### ISSUE THREAD

**Issue by pakotzy** [melloware/jintellitype#17]
With Spring Boot, to load a resource file from inside of the JAR package you must use ResourceLoader which returns InputStream, because any other access method will cause IOException while launching from outside of the IDE.
Since JIntellitype is already using InputStream under the hood, it will be nice to be able to provide it manually for better flexibility as requested in #16

**Comment by melloware** [comment]
Thanks PR merged!
