### ISSUE TITLE
Readme file should be written in Markdown

### ISSUE THREAD

**Issue by Jiawens** [melloware/jintellitype#18]
Using a txt file will result in an unsightly layout and unclear.
Therefore you should use Markdown.
(Sorry,I may not be too polite, please forgive me.)

**Comment by melloware** [comment]
I absolutely agree.  Are you interested in helping format it?  I would be happy to include it if you e-mailed or ever better submitted a PR with the changes?

**Comment by Jiawens** [comment]
Thank you for accepting my advice. I am happy to help you. I will submit it in the form of PR in the next few days.
