### ISSUE TITLE
一些window10的问题?/Some window10 problems?

### ISSUE THREAD

**Issue by IchiehPan** [melloware/jintellitype#22]
我的java版本是11.0.1, 在windows10_1809 'regHotKey(identifier, modifier, keycode);'报错.
然后我尝试了虚拟机使用windows7版本是正常的.

---
My java version is 11.0.1, in windows10_1809 'regHotKey(identifier, modifier, keycode); 'Report error.
Then I tried the virtual machine using the windows7 version is normal.

**Comment by melloware** [comment]
I don't think its Windows 10. Its JDK 11 that is causing the issue.  

See here: https://github.com/melloware/jintellitype/issues/21
