### ISSUE TITLE
Load DLL's from inside JAR

### ISSUE THREAD

**Issue by jjYBdx4IL** [melloware/jintellitype#23]
The code failed to load the dll from jar because the jar file on maven central does not contain the dll.

**Comment by melloware** [comment]
Yes we did not package the DLL. See our instructions in the readme.txt here: https://github.com/melloware/jintellitype/blob/master/readme.txt

**Comment by jjYBdx4IL** [comment]
for a better adoption I recommend packaging with the jar.

**Comment by melloware** [comment]
Yep I reopened this ticket that is a good idea. Do you have an example library you can point me to that packages them inside the JAR?

**Comment by jjYBdx4IL** [comment]
open resource-stream, copy it to a file named System.getProperty("user.home")+"/AppData/LocalLow/jintellitype/jni-"+version+".dll" if that does not exist alrady, then use System.load to load it. Should work that way if there are all dependent libraries available on the system. If loading fails, remove and replace the existing extracted dll because it may have been corrupted. Some people also simply extract the dll to the temp folder and register a VM shutdown hook to remove it, but that's inferior because it's slower because it doesn't get cached and always needs to be extracted.

Ofc if you really want to do the extraction correctly, you need a blocking lock on the containing folder.
