### ISSUE TITLE
JavaFX

### ISSUE THREAD

**Issue by unclezs** [melloware/jintellitype#25]
![image](https://user-images.githubusercontent.com/42318775/62184421-994af600-b390-11e9-8e12-0d9389376a44.png)
![image](https://user-images.githubusercontent.com/42318775/62184467-cac3c180-b390-11e9-9012-267c90f0689f.png)

在非javaFX应用中能够正常加载，如图，32位不能够正常初始化，64位的可以正常使用

**Comment by melloware** [comment]
Yes please place JIntellitype.dll or Jintellitype64.dll in C:\Windows\ directory.

**Comment by unclezs** [comment]
I always put DLL in C: Windows directory, I can run 64-bit DLL normally in 64-bit jre8, but after replacing 32-bit JRE with 32-bit jre, I can not initialize 32-bit dll, which shows initialization failure. After my investigation, it is because in the case of javaFX application, it can initialize 32-bit DLL normally in non-javaFx application.
