### ISSUE TITLE
could not load DLL

### ISSUE THREAD

**Issue by Aubrey-J** [melloware/jintellitype#27]
JIntellitype类中：line 131：System.load(extractedLibrary.getAbsolutePath());，在配置Native Library Path后，依然提示could not load DLL；
在我修改使用System.loadLibrary("JIntellitype64");，就可以了，请问是否可以？
参数可获取String libraryName变量去电.dll，不可以带扩展名

**Comment by melloware** [comment]
Yes please place JIntellitype.dll or Jintellitype64.dll in C:\Windows\ directory.

**Comment by Aubrey-J** [comment]
好的，谢谢！

**Comment by melloware** [comment]
English only please.

**Comment by Aubrey-J** [comment]
yeah,Thank you very much,my problem solved,I am English is not good

**Comment by melloware** [comment]
Excellent!
