### ISSUE TITLE
Hotkey Distinguish KeyUp from KeyDown

### ISSUE THREAD

**Issue by chensiweipsp** [melloware/jintellitype#44]
如何区分单个按键的按下和抬起？

        举例 ：JIntellitype.getInstance().registerHotKey(UserKeyBoardEnum.DUNHAO.getKeyValue(), 0,
                UserKeyBoardEnum.DUNHAO.getKeyValue());

0 表示  按下和抬起全部都执行   
那么如何单独区分呢？

**Comment by melloware** [comment]
English only please.

**Comment by chensiweipsp** [comment]
How to distinguish the pressing and lifting of a single key?

Example: jintellitype. Getinstance(). Registerhotkey (userkeyboardenum. Dunhao. Getkeyvalue(), 0,

UserKeyBoardEnum.DUNHAO.getKeyValue());

0 means that pressing and lifting are all performed

So how to distinguish it separately?

**Comment by melloware** [comment]
Unfortunately you cannot distinguish them.  Microsoft just emits a "hotkey" event has happened on your registered hotkey.
