### ISSUE TITLE
Can't register slash and back slash key

### ISSUE THREAD

**Issue by fangshenghan** [melloware/jintellitype#62]
Can't register slash and back slash key
JIntellitype.getInstance().registerHotKey(1, 0, KeyEvent.VK_SLASH);
JIntellitype.getInstance().registerHotKey(2, 0, KeyEvent.VK_BACK_SLASH);
It doesn't work :(

**Comment by melloware** [comment]
Do this...

```java
JIntellitype.getInstance().registerHotKey(1, "slash");
JIntellitype.getInstance().registerHotKey(2, "back_slash");
```

**Comment by melloware** [comment]
You can see all the keymappings defined here:

https://github.com/melloware/jintellitype/blob/6604cb3f31df94fd42044f0c94fc919f46fb04d7/src/main/java/com/melloware/jintellitype/JIntellitype.java#L446-L640
