### ISSUE TITLE
Error thrown as a result of missing library

### ISSUE THREAD

**Issue by RocketMaDev** [melloware/jintellitype#66]
It was when I was using my program equipped with `jintellitype` on other's computer when it got crashed, telling me that some dependencies are missing, causing a unexpected error. I think it may require the latest `vcrt`. As I'm still learning C++, I'm sure one day I will use gcc to compile it and may refactor some code that can be optimized.

**Comment by melloware** [comment]
+1 !!

**Comment by RocketMaDev** [comment]
@melloware I've scanned it's dependencies and found my guess right. Just download the latest vcrt and it works fine.

**Comment by melloware** [comment]
So can this be closed?
