### ISSUE TITLE
i can't understand intellitype and What can be achieved through it

### ISSUE THREAD

**Issue by DengYuncheng27** [melloware/jintellitype#79]
In jintellitype , there are two method - onHotKey and onIntellitype.
I do understand what can do in onHotKey , it listen keybords and when i press some keys the program will react it . 
But i can understand what the intellitype does , i don't know what can be achieved through onItellitype method，and don't know how to touch it in JIntellitypeDemo.java。
![image](https://user-images.githubusercontent.com/56923863/194578878-0817596c-4e63-4823-aec3-f371eb175d37.png)

**Comment by melloware** [comment]
For Intellitype commands like PAUSE and PLAY etc usually you have to have a Media Keyboard that has those buttons or in some cases Microsoft used to have a remote control for their Media Cetner Edition PC's which would also emit PLAY, PAUSE, STOP etc.

**Comment by DengYuncheng27** [comment]
thank you for your patient anwser , i have find a keyboard image that have media keys, thank you.
![image](https://user-images.githubusercontent.com/56923863/194678125-e7effa1a-b780-4d64-9936-7b84baa635d4.png)
