### ISSUE TITLE
when JIntellitypeDemo running and registerHotKey  , some key does not work

### ISSUE THREAD

**Issue by DengYuncheng27** [melloware/jintellitype#80]
when the demo running , some key does not work , like ' c ' , ' ; ' in keybord. 
system version : win 11.

**Comment by melloware** [comment]
some might be blocked by Windows 11.  It used to allow all keys not Microsoft doesn't allow some keys to be bound as hotkeys.

**Comment by DengYuncheng27** [comment]
I can understand it now  . Thank you for your patience.
